Support LocaleConfig in Terminal.init (#82)
LocaleConfig was added to a recent Terminal SDK release. 

Migrate off of the now-deprecated init call and pass in a LocaleConfig
to fix compilation error:
> e: warnings found and -Werror specified


See
https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-locale-config/index.html
for more details

# How has this been tested?
- [X] Manual

## Reproducible test instructions
Stripe.init still works on my Stripe S700 devkit device